///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace JiraDemoSolution
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the JiraDemoSolutionRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("07da7171-552f-4cfd-b435-69a3811e3e39")]
    public partial class JiraDemoSolutionRepository : RepoGenBaseFolder
    {
        static JiraDemoSolutionRepository instance = new JiraDemoSolutionRepository();
        JiraDemoSolutionRepositoryFolders.GoogleAppFolder _google;

        /// <summary>
        /// Gets the singleton class instance representing the JiraDemoSolutionRepository element repository.
        /// </summary>
        [RepositoryFolder("07da7171-552f-4cfd-b435-69a3811e3e39")]
        public static JiraDemoSolutionRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public JiraDemoSolutionRepository() 
            : base("JiraDemoSolutionRepository", "/", null, 0, false, "07da7171-552f-4cfd-b435-69a3811e3e39", ".\\RepositoryImages\\JiraDemoSolutionRepository07da7171.rximgres")
        {
            _google = new JiraDemoSolutionRepositoryFolders.GoogleAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("07da7171-552f-4cfd-b435-69a3811e3e39")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Google folder.
        /// </summary>
        [RepositoryFolder("ec84a993-a936-4092-9685-d379cdbff1e9")]
        public virtual JiraDemoSolutionRepositoryFolders.GoogleAppFolder Google
        {
            get { return _google; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class JiraDemoSolutionRepositoryFolders
    {
        /// <summary>
        /// The GoogleAppFolder folder.
        /// </summary>
        [RepositoryFolder("ec84a993-a936-4092-9685-d379cdbff1e9")]
        public partial class GoogleAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lstibInfo;
            RepoItemInfo _buttonInfo;

            /// <summary>
            /// Creates a new Google  folder.
            /// </summary>
            public GoogleAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Google", "/dom[@domain='www.google.at']", parentFolder, 30000, null, false, "ec84a993-a936-4092-9685-d379cdbff1e9", "")
            {
                _lstibInfo = new RepoItemInfo(this, "LstIb", ".//input[#'lst-ib']", 30000, null, "dbbc7359-ddb8-4d8f-9c69-bcc606078b77");
                _buttonInfo = new RepoItemInfo(this, "Button", ".//div[#'sbtc']//input[@type='button']", 30000, null, "be5a7404-da9c-447b-a5ef-7d8a3f4b8290");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ec84a993-a936-4092-9685-d379cdbff1e9")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ec84a993-a936-4092-9685-d379cdbff1e9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LstIb item.
            /// </summary>
            [RepositoryItem("dbbc7359-ddb8-4d8f-9c69-bcc606078b77")]
            public virtual Ranorex.InputTag LstIb
            {
                get
                {
                    return _lstibInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LstIb item info.
            /// </summary>
            [RepositoryItemInfo("dbbc7359-ddb8-4d8f-9c69-bcc606078b77")]
            public virtual RepoItemInfo LstIbInfo
            {
                get
                {
                    return _lstibInfo;
                }
            }

            /// <summary>
            /// The Button item.
            /// </summary>
            [RepositoryItem("be5a7404-da9c-447b-a5ef-7d8a3f4b8290")]
            public virtual Ranorex.InputTag Button
            {
                get
                {
                    return _buttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Button item info.
            /// </summary>
            [RepositoryItemInfo("be5a7404-da9c-447b-a5ef-7d8a3f4b8290")]
            public virtual RepoItemInfo ButtonInfo
            {
                get
                {
                    return _buttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}